title: Tome of Heroes
description: Data and Analysis of Fire Emblem Heroes
theme: just-the-docs

url: https://jecDSC.github.io/tome-of-heroes-site

aux_links:
  Template Repository: https://github.com/jecDSC/tome-of-heroes-site
